#pragma once

namespace XBase {

enum class CapabilitySupport {
    Unsupported,
    Partial,
    Supported,
};

enum class Capability {
    Player,
    Ped,
    Vehicle,
    World,
    Weapon,
    Scene,
    Visual,
    Teleport,
    Overlay,
    BulletAssist,
    Camera,
    Cheats,
    VehicleEffects,
    Hooks,
    Ui,
};

enum class FeatureCapability {
    PlayerBasicState,
    PlayerRuntimeEffects,
    PlayerProofs,
    PlayerMovement,
    PlayerAppearance,
    PlayerClothes,
    PlayerStats,
    PlayerSuperJump,
    PlayerSuperPunch,
    PlayerUnderwaterBreathing,
    PlayerCycleJump,
    PlayerNeverHungry,
    PlayerFastSprint,
    PlayerSprintEverywhere,
    PlayerDrunkEffect,
    PlayerNeverWanted,
    PlayerAimSkinChanger,
    PlayerKeepStuff,
    PlayerSaveGame,
    PedBasic,
    PedSpawn,
    PedDelete,
    PedAttributes,
    PedClassification,
    PedMarkerSpawn,
    PedGlobalStrategies,
    PedBigHead,
    PedThinBody,
    PedSmokeFlies,
    VehicleBasic,
    VehicleColors,
    VehicleDoors,
    VehicleSpawn,
    VehicleSpawnSession,
    VehicleDelete,
    VehicleEvents,
    VehiclePopDoors,
    VehicleAlwaysSkidMarks,
    VehicleDisableParticles,
    VehicleDriverTargetable,
    VehicleHeatSeekingTargetable,
    VehiclePetrolTankWeakPoint,
    VehicleSirenOrAlarm,
    VehicleTakeLessDamage,
    VehicleTrafficDensity,
    VehicleAutoDrive,
    VehiclePaintjob,
    VehicleUpgrades,
    VehicleCheats,
    WorldTime,
    WorldWeather,
    WorldGravity,
    WorldPickups,
    WorldGameSpeed,
    WorldFpsLimit,
    WorldDaysPassed,
    WorldFreezeTime,
    WorldFasterClock,
    WorldDisableReplay,
    WorldDisableCheats,
    WorldForbiddenAreaWanted,
    WorldFreePayNSpray,
    WorldNoWaterPhysics,
    WorldSolidWater,
    WeaponBasic,
    WeaponGive,
    WeaponDrop,
    WeaponSkills,
    WeaponRuntimeEffects,
    WeaponStatOverrides,
    BulletAssistTracking,
    BulletAssistThroughWalls,
    BulletAssistHardLock,
    BulletAssistPedBounds,
    BulletAssistPedCollision,
    BulletAssistPedSkeleton,
    BulletAssistVehicleBounds,
    BulletAssistVehicleCollision,
    BulletAssistFireSuppression,
    CameraFreecam,
    CameraTopDown,
    CheatsRandom,
    VehicleEffectsNeon,
    SceneAnimation,
    SceneParticle,
    SceneCutscene,
    SceneMission,
    TeleportBasic,
    VisualHudRadar,
    VisualFilter,
    VisualRadarOptions,
};

// Domain queries are retained for compatibility. New integrations should use
// feature queries so a partially implemented backend is never over-reported.
CapabilitySupport GetCapabilitySupport(Capability capability);
CapabilitySupport GetCapabilitySupport(FeatureCapability capability);
bool HasCapability(Capability capability);
bool HasCapability(FeatureCapability capability);

} // namespace XBase